as yet unclassified
attachmentPointsSpecs
	^ {
		"{#center. #color. #borderColor}"
		{self center + (0@ -72). Color black. Color gray}.
		{self center + (-11@ -72). Color black. Color gray}.
		{self center + (-22@ -72). Color black. Color gray}.
		{self center + (-33@ -72). Color black. Color gray}.
		{self center + (-89@ -72). Color black. Color gray}.
		{self center + (-111@ -72). Color black. Color gray}.
	}