private
initializeWithFriendlyNames: anArray fCpu: anInteger mcu: aString uploadRate: uploadRate1 firmataRate: firmataRate1 avrdudeProgrammer: programmerString analogPins: analogPins1 digitalPins: digitalPins1
	self initialize.
	friendlyNames := anArray.
	fCpu := anInteger.
	mcu := aString.
	uploadRate := uploadRate1.
	firmataRate := firmataRate1.
	programmer := programmerString.
	analogPins := analogPins1.
	digitalPins := digitalPins1