SystemOrganization addCategory: #'CTranslator-Hierarchy'!
SystemOrganization addCategory: #'CTranslator-Utilities'!
SystemOrganization addCategory: #'CTranslator-Translators-Cpp'!
SystemOrganization addCategory: #'CTranslator-Translators-C'!
SystemOrganization addCategory: #'CTranslator-Exceptions'!
SystemOrganization addCategory: #'CTranslator-Programs'!
SystemOrganization addCategory: #'CTranslator-Output-Cpp'!
SystemOrganization addCategory: #'CTranslator-Output-C'!
