definition
subclass: nameOfClass instanceVariableNames: instVarNames instanceVariableTypes: instVarTypes classVariableNames: classVarNames poolDictionaries: poolDictnames category: category1 includes: includesArray
	^ (self
		subclass: nameOfClass
		instanceVariableNames: instVarNames
		instanceVariableTypes: instVarTypes 
		classVariableNames: classVarNames
		poolDictionaries: poolDictnames
		category: category1)
		includes: includesArray