viewer categories
additionsToViewerCategories
^ #(
(#'keypad' (
#(slot #'row 1, column 1' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue11 Player unused  )
#(slot #'row 1, column 2' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue12 Player unused  )
#(slot #'row 1, column 3' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue13 Player unused  )
#(slot #'row 2, column 1' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue21 Player unused  )
#(slot #'row 2, column 2' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue22 Player unused  )
#(slot #'row 2, column 3' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue23 Player unused  )
#(slot #'row 3, column 1' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue31 Player unused  )
#(slot #'row 3, column 2' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue32 Player unused  )
#(slot #'row 3, column 3' 'Shows if this button is pressed' Boolean readOnly Player getButtonValue33 Player unused  )
))
)
