introspection
readmeText
	^ 'Skeleton ', self class version, '

Skeleton is a easy scripting system with spreadsheet-like user interface.  It handles an etoy''s slot as a spread sheet''s cell. So user can describe declarative rules among morphs as spread sheet''s "=A1 +A2" style. It is similar with Visio''s "shape sheet", but Skeleton-sheet has more dynamic and real-time behavior.

Takashi Yamamiya <propella@yuri.sakura.ne.jp>
http://languagegame.org:8080/ggame/11

SkSheet example

2004-04-10
	Fix some dirty code (Remove references of Transcript, Fix a word in world menu).
	Support Babel.
'