translations
missingStrings
	"This is just to ensure certain strings from Etoys are findable by the translator"

	"UserCustomEventNameType>>#choices"
	'no event' translatedNoop.

	"From PE main project"
	'Click here to open Physical Etoys' translatedNoop.
	'Click here to open Etoys' translatedNoop.

	"From PE home project"
	'New
project' translatedNoop.
	'Examples' translatedNoop.

	"From PE arduino, DuinoBot and Lego Nxt example projects"
	'The "Hello World" of Electronics' translatedNoop.
	'Start by choosing the type and the corresponding serial port for your Arduino board and click "Connect".' translatedNoop.
	'Then start the script below by clicking the iconic button that looks like a clock.' translatedNoop.
	'A bit of magic' translatedNoop.
	'Plug a motor in port A and a sound sensor in port 1 of your Lego Nxt.
Then choose the serial port for the connection with your Lego Nxt and click "Connect".' translatedNoop.
	'Start the script below by clicking the icon that looks like a clock.
Now make noise around your robot and watch how the motor moves.' translatedNoop.
	'Connection status:' translatedNoop.
	'Connect' translatedNoop.
	'Disconnect' translatedNoop.
	'Connected' translatedNoop.
	'Disconnected' translatedNoop.
	'This is just an example. You can do a lot of other stuff with Physical Etoys!' translatedNoop.
	'Click here to learn more!' translatedNoop.
	'Start by choosing the type and the corresponding port for your DuinoBot and click "Connect".' translatedNoop.

	"From the 'Examples' project"
	'Load a project' translatedNoop.
	'By {1}' translatedNoop.

	"From the projects in the examples dir"
	'Arduino-StreetLight' translatedNoop.
	'This project shows the behavior of an automatic street light, which detects itself wether there is need for light or not.' translatedNoop.
	'Arduino-TrafficLight' translatedNoop.
	'This project uses three leds to simulate the behavior of a traffic light.' translatedNoop.
	'DuinoBot-Concurrency' translatedNoop.
	'A demonstration of multiple scripts running at the same time.' translatedNoop.
	'DuinoBot-Graph' translatedNoop.
	'This project plots the input of the analog pin 0 over time.' translatedNoop.
	'DuinoBot-Greenhouse' translatedNoop.
	'This project simulates a temperature controlled greenhouse. It uses a thermistor to sense the temperature, and a motor to represent a fan.' translatedNoop.
	'DuinoBot-Motors' translatedNoop.
	'This project moves the motors 2 seconds in one direction, then 2 seconds in the opposite direction, and then it stops them.' translatedNoop.
	'DuinoBot-RemoteControl' translatedNoop.
	'This project shows how you can use a remote control to interact with your DuinoBot.' translatedNoop.
	'LegoNxt-Car' translatedNoop.
	'This project shows how to program a car that can be remotely controlled with the keyboard or a joystick.' translatedNoop.
	'LegoNxt-DodgeWalls' translatedNoop.
	'This project shows how to program a car that avoids obstacles.' translatedNoop.
	'photoresistor' translatedNoop.
	'concurrency' translatedNoop.
	'graph' translatedNoop.
	'ultrasonic' translatedNoop.
	'infrared receiver' translatedNoop.
	'remote control' translatedNoop
	